parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
included-patches = "'Enable slide to seek' 'Custom branding'"
patcher-args = "-OappName=YouTube "

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"
excluded-patches = "'Change link sharing domain'"

[Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"

[Lightroom]
apkmirror-dlurl = "https://apkmirror.com/apk/adobe/lightroom/"
arch = "arm64-v8a"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
