parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
included-patches = "'Enable slide to seek' 'Custom branding'"
patcher-args = "-OappName=YouTube "

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"

[Twitter]
build-mode = "apk"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"
excluded-patches = "'Change link sharing domain'"

[GooglePhotos]
build-mode = "apk"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Lightroom]
apkmirror-dlurl = "https://apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "9.0.36.683"
